version: "3.9"

services:
  app:
    build: ./volumes
    container_name: 'app-ceritamed'
    restart: 'always'
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - SECRET_KEY=vsi^pgp1hr=k*30z55+nzb2(n4r8n#ti)(-!!zvs9!j08yf&sb
      - SETTING=core.settings.development
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=ceritamed
      - SQL_USER=ceritamed
      - SQL_PASSWORD=Amir@1995
      - SQL_HOST=db
      - SQL_PORT=5432
    volumes:
      - ./volumes/core:/app
      - ./volumes/static:/static
      - ./volumes/media:/media
    depends_on:
      - db
      - nginx
      
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - .volumes/db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ceritamed
      - POSTGRES_USER=ceritamed
      - POSTGRES_PASSWORD=Amir@1995

  nginx:
    build: ./nginx
    volumes:
      - ./volumes/static:/static
      - ./volumes/media:/media
    ports:
      - 80:80

volumes:
  postgres_data: