# Generated by Django 3.1 on 2023-11-19 08:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ارسال')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / خوانده نشده')),
                ('is_result', models.TextField(blank=True, null=True, verbose_name='نتیجه پیگیری')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='اخرین به روزرسانی')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='ایمیل')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('where', models.URLField(blank=True, max_length=300, null=True, verbose_name='صفحه ارسال فرم')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / خوانده نشده')),
                ('is_result', models.TextField(blank=True, null=True, verbose_name='نتیجه پیگیری')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سن')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, null=True, verbose_name='جنس')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('sickness', models.CharField(blank=True, max_length=100, null=True, verbose_name='بیماری')),
                ('absorption_channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='کانال جذب')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('follow_up_1', models.BooleanField(default=False, verbose_name='دو روز بعد')),
                ('follow_up_2', models.BooleanField(default=False, verbose_name='دو هفته بعد')),
                ('follow_up_3', models.BooleanField(default=False, verbose_name='یک ماه بعد')),
                ('follow_up_4', models.BooleanField(default=False, verbose_name='یک سال بعد')),
            ],
            options={
                'verbose_name': 'فرم',
                'verbose_name_plural': 'فرم ها',
                'ordering': ['-created_date'],
            },
        ),
    ]
