# Generated by Django 3.1 on 2023-11-22 13:00

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Active / Deactivate')),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Delete / Not Delete')),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='Slug (URl)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('meta_canonical', models.URLField(blank=True, null=True, verbose_name='Canonical')),
                ('icon', models.ImageField(upload_to='service-category/icon', verbose_name='Icon')),
                ('img', models.ImageField(null=True, upload_to='service-category', verbose_name='Image')),
                ('index', models.BooleanField(default=False, verbose_name='Show in index page')),
                ('changed_active_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeservices_servicecategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('changed_deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletedservices_servicecategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdservices_servicecategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedservices_servicecategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Active / Deactivate')),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Delete / Not Delete')),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='Slug (URl)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('meta_canonical', models.URLField(blank=True, null=True, verbose_name='Canonical')),
                ('img', models.ImageField(null=True, upload_to='services', verbose_name='Image')),
                ('icon', models.ImageField(max_length=15, null=True, upload_to='service/icon', verbose_name='Icon')),
                ('price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('index', models.BooleanField(default=False, verbose_name='Show in index page')),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='services.ServiceCategory', verbose_name='Category')),
                ('changed_active_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeservices_service_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('changed_deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletedservices_service_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdservices_service_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedservices_service_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
