# Generated by Django 3.2 on 2023-11-17 06:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import services.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.CharField(help_text='این عنوان داخل تگ title قرار میگیره', max_length=150, null=True, verbose_name='عنوان Seo')),
                ('title', models.CharField(help_text='این عنوان اصلی خدمت هستش ( پروتز دنداد و امپلنت ...)', max_length=150, verbose_name='عنوان خدمت')),
                ('h1', models.CharField(max_length=65, null=True, verbose_name=' تگ H1')),
                ('img', models.ImageField(null=True, upload_to=services.models.upload_image_path_Servise, verbose_name='عکس')),
                ('png_img', models.FileField(null=True, upload_to=services.models.upload_image_path_servise_icons, verbose_name='ایکون')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL خدمت')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت خدمت')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='متا دیسکریپشن')),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوا')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاریخ انتشار')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
                ('active_home', models.BooleanField(default=False, verbose_name='صفحه اول سایت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمت ها',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خدمت')),
                ('png_img', models.FileField(help_text='ابعاد مناسب 30 * 30 px', null=True, upload_to=services.models.upload_image_path_servise_icons, verbose_name='ایکون')),
                ('png_img_home', models.FileField(help_text='ابعاد مناسب 35 * 35 px', null=True, upload_to=services.models.upload_image_path_servise_icons, verbose_name='ایکون صفحه اصلی')),
                ('img', models.ImageField(null=True, upload_to=services.models.upload_image_path, verbose_name='عکس')),
                ('descriptions', models.TextField(max_length=200, null=True, verbose_name='توضیح کوتاه')),
                ('slug', models.SlugField(unique=True, verbose_name='url صفحه')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
                ('active_home', models.BooleanField(default=False, verbose_name='صفحه اول سایت')),
            ],
            options={
                'verbose_name': 'دستته خدمت',
                'verbose_name_plural': 'دسته خدمت ها',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم کشور')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت به دلار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'تفاوت قیمت',
                'verbose_name_plural': 'تفاوت قیمت',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='s_category',
            field=models.ManyToManyField(blank=True, related_name='Servise_category', to='services.ServiceCategory', verbose_name='دسته بندی خدمات'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها و کلمات کلیدی'),
        ),
    ]
