# Generated by Django 3.1 on 2023-11-22 13:00

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('problem', models.CharField(max_length=50, verbose_name='بیماری درمان شده')),
                ('img', models.ImageField(help_text='ابعاد عکس 85 * 85 px', null=True, upload_to=settings.models.upload_image_path_customers, verbose_name='عکس مشتری')),
                ('text', models.TextField(verbose_name='نظره مشتری')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظر مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('img', models.FileField(help_text='ابعاد عکس 45 * 45 px و کده رنگ #19ce67', null=True, upload_to='Home_data_icons', verbose_name='ایکون')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
            ],
            options={
                'verbose_name': 'امار سایت',
                'verbose_name_plural': 'امار های سایت',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('img', models.FileField(help_text='ابعاد عکس 164 * 82', null=True, upload_to=settings.models.upload_image_path_partners, verbose_name='عکس لوگو')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
            ],
            options={
                'verbose_name': 'پارتنر',
                'verbose_name_plural': 'پارتنر ها',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='عنوان')),
                ('category', models.CharField(max_length=65, null=True, verbose_name='دسته بندی')),
                ('img', models.ImageField(null=True, upload_to=settings.models.upload_image_path, verbose_name='عکس پس زمینه')),
                ('btn', models.CharField(blank=True, default='کلیک کنید', help_text='متن پیش فرض ( کلیک کنید ) هستش', max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('descriptions', models.TextField(verbose_name='محتوا')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
            ],
            options={
                'verbose_name': 'اسلادر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
