# Generated by Django 4.2.7 on 2023-12-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_alter_feedback_id_alter_partnercompany_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='setting',
            name='short_about',
            field=models.TextField(blank=True, null=True, verbose_name='Short about'),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Active / Deactivate')),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Delete / Not Delete')),
                ('url', models.URLField(verbose_name='Link')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('changed_active_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('changed_deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
    ]
