# Generated by Django 4.2.7 on 2023-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_setting_logo_setting_dark_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='dark_logo',
            field=models.ImageField(null=True, upload_to='setting/logo', verbose_name='Dark logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='light_logo',
            field=models.ImageField(null=True, upload_to='setting/logo', verbose_name='Light logo'),
        ),
    ]
