# Generated by Django 4.2.7 on 2023-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_setting_dark_logo_alter_setting_light_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='partnercompany',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
