# Generated by Django 4.2.7 on 2023-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_social_order_alter_partnercompany_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnercompany',
            old_name='order',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='order',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='order',
        ),
        migrations.RemoveField(
            model_name='social',
            name='order',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='slider',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='social',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
