# Generated by Django 4.2.7 on 2023-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_rename_order_partnercompany_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='partnercompany',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='social',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
    ]
