# Generated by Django 3.1 on 2023-11-19 06:48

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='عنوان Seo')),
                ('h1', models.CharField(max_length=100, null=True, verbose_name='h1')),
                ('img', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر اصلی مقاله')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='متا دیسکریپشن')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name=' مقاله url')),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوا')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاریخ انتشار دستی')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='بروز رسانی')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیره فعال')),
                ('blog_views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
                'ordering': ['-publish'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='اپدیت')),
                ('active', models.BooleanField(default=False, verbose_name='فال و غیر فعال')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'کامنتپ',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='b_category',
            field=models.ManyToManyField(blank=True, related_name='blog_category', to='blog.PostCategory', verbose_name='دسته بندی بلاگ'),
        ),
    ]
