# Generated by Django 3.1 on 2023-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterField(
            model_name='article',
            name='visit',
            field=models.IntegerField(default=0, editable=False, verbose_name='Visits'),
        ),
    ]
