# Generated by Django 3.1 on 2021-02-07 07:49

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Ceritamed_Blog', '0001_initial'),
        ('Ceritamed_Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_Expertiseee', to='Ceritamed_Doctors.doctorexpertise', verbose_name='پزشک های مرتبط'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها و کلمات کلیدی'),
        ),
    ]
